* Langevin MCMC and its M-H acceptance probability
  The acceptance probability of an MCMC sampler that follows the Langevin
  stochastic differential equations (SDE) is always 1. However, to be able to
  simulate the SDE, we discretise the time steps, and in so introduce error.
  This error can be exactly corrected (cite:sarkka_solin_2019) by adding a
  Metropolis-Hastings (M-H) step, that applies rejection sampling for the new
  state of the SDE. Additional error is introduced by the approximate
  floating-point arithmetic, but we will disregard it.

  In Langevin MCMC, we have some parameters $\theta$ to be inferred (also named
  /position variables/), and their corresponding /momentum variables/ $m$. The
  generalised Metropolis-Hastings acceptance probability (cite:song2020hams),
  which negates the final momentum, is as follows. If a transition goes from 
  $(\theta_0, m_0) \to (\theta_*, m_*)$, its acceptance probability is
  \begin{equation}
    \text{Pr}_\text{accept}(\theta_*, m_*) = \text{min}\left(1,
        \frac{\pi(\theta_*) T(\theta_0, -m_0 | \theta_*, -m_*)}
            {\pi(\theta_0) T(\theta_*, m_* | \theta_0, m_0)} \right)
  \end{equation}
  for transition probability density $T$ and target distribution density $\pi$.
  If a sample $(\theta_*, m_*)$ is rejected, we have to set the next state of
  the chain to $(\theta_0, -m_0)$ (and not $(\theta_0, m_0)$ like ordinary
  Metropolis-Hastings)$.

  It is important to note that the transition probability distribution $T$, and
  thus the acceptance probability, very much depend on the scheme we use to
  discretise time in the SDE. That is, the integrator.
  
** Symplectic Euler integrator 
     The Symplectic Euler integrator used in cite:wenzel20posterior is not
     time-reversible. This implies that the probability of transitioning
     $(\theta_*, -m_*) \to (\theta_0, m_0)$ is always zero, strictly speaking.
     This is because the value of $\theta_*$ is determined entirely by the
     previous parameters, $\theta_0$, and its *contemporaneous* momentum $m_*$.
     The forward transition for the parameters is
     \begin{equation}
        \theta_* = \theta_0 + h M^{-1} m_*.
     \end{equation}
     
     Now, consider what the backward transition would be. The momentum $-m_*$
     evolves to $-m_0$, and the parameters $\theta_*$ evolve to $\theta_0$. The
     transition, now applied backward, is
     \begin{equation}
        \theta_0 = \theta_* + h M^{-1} (-m_0),
     \end{equation}
     which *cannot* be true if $m_0 \ne m_*$.
